#ifndef HARDWARE_WALLET_SKYCOINAPI_TOOLS_BIP32
#define HARDWARE_WALLET_SKYCOINAPI_TOOLS_BIP32

#include <check.h>

void load_bip32_testcase(Suite* s);

#endif  // HARDWARE_WALLET_SKYCOINAPI_TOOLS_BIP32
